terminate called after throwing an instance of 'std::runtime_error'
  what():  could not load data from myfile.txt
bash: line 7: 29590 Aborted                 (core dumped) ./a.out
