Caught exception: foo::bar()::error
