terminate called after throwing an instance of 'std::logic_error'
  what():  doh
bash: line 7: 31115 Aborted                 (core dumped) ./a.out
