terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
bash: line 7: 13008 Aborted                 (core dumped) ./a.out <<< INPUT
bash: line 8: 5: command not found
bash: line 9: 0: command not found
bash: line 10: 0: command not found
bash: line 11: 1: command not found
bash: line 12: 1: command not found
bash: line 13: 3: command not found
bash: line 14: 2: command not found
bash: line 15: INPUT: command not found
