terminate called after throwing an instance of 'std::runtime_error'
  what():  random_device::random_device(const std::string&)
bash: line 6: 21676 Aborted                 (core dumped) ./a.out
